### ISSUE TITLE
L'image suivante à la section 9.9 devrait être une figure

### ISSUE THREAD

**Issue by Olon11** [fuhrmanator/log210-ndc-quarto#102]
<img width="259" alt="image" src="https://user-images.githubusercontent.com/15785239/218287137-ddc510dc-2bbc-434d-87bf-38d400c8a39a.png">

**Comment by fuhrmanator** [comment]
Tu n'as pas dit pourquoi. 

Le problème avec les figures avec les légendes (fig X) est que dans LaTeX (format PDF) c'est un environnement "float" qui fait en sorte que l'algo de la mise en page va la placer où il veut (en haut de la page, qui peut être après ou avant l'exercice) et je trouvais ça moins bien (surtout de devoir écrire "voir la figure X" dans l'exercice). 

En format HTML ce problème n'existe pas. Alors, je voudrais fermer ce point, sauf si tu as une raison pour laquelle c'est un problème.

**Comment by Olon11** [comment]
C'est pour être cohérent avec la figure 9.8. Par contre, je ne crois pas que c'est un problème important. On pourrait la laisser comme ça si ça cause un problème dans la mise en page.
