### ISSUE TITLE
Corrections à la section Remerciements

### ISSUE THREAD

**Issue by Olon11** [fuhrmanator/log210-ndc-quarto#103]
- [ ] Puisqu'on a déjà défini l'acronyme ÉTS, on a pas à répéter « École de technologie supérieure ».
- [ ] On devrait plutôt lire : Olivier Brochu, étudiant à la maîtrise et au doctorat en génie des technologies de l'information à l’ÉTS ;
- [x] Dans la phrase « professeur au département de génie logiciel et des TI », TI n'est pas défini.

**Comment by fuhrmanator** [comment]
@Olon11 j'ignorais que tu peux être étudiant à la maîtrise et au doctorat en même temps. Si c'est le passage bacc-doc je pensais que le diplôme de maîtrise n'y figurait pas, sauf si on ne termine pas le doc (je n'ai moi-même pas de maîtrise).

**Comment by fuhrmanator** [comment]
Il n'est pas faux, selon moi, de répéter le sens d'un acronyme ÉTS (surtout pour être cohérent avec la section où on mentionne toutes les personnes des universités différentes). Mme Moumene de la bibliothèque avait justement proposé de ne pas faire l'acronyme.

**Comment by Olon11** [comment]
Oui, les deux programmes peuvent se chevaucher. Je ne fait pas la passerelle, je vais avoir les deux diplômes (et mes projets n'ont pas de lien).

> Mme Moumene de la bibliothèque avait justement proposé de ne pas faire l'acronyme.

Pas de problème

**Comment by fuhrmanator** [comment]
Les balises éditoriales nécessitent des remerciements plus sobres, alors le statut des gens n'est pas mentionné.
