### ISSUE TITLE
Idée d'exercice : création d'un MDD par rétroingénierie

### ISSUE THREAD

**Issue by Olon11** [fuhrmanator/log210-ndc-quarto#107]
J'ai pensé à un exercice guidé où le lecteur pourrait analyser le logiciel Discord et réaliser le MDD par rétroingénierie. L'exercice aurait les étapes suivantes :
1. Parcourir le logiciel Discord pour en identifier les fonctionnalités. Discord permet de se créer un compte temporaire sans adresse courriel. Ça permet de rendre l'exercice accessible à tous
2. Identifier les classes conceptuelles en lien avec les concepts présents dans Discord et la liste de catégories de classes conceptuelles
3. Identifier les attributs de chaque classe conceptuelle
4. Identifier les associations entre les classes et leurs cardinalités

Je crois que c'est un exercice intéressant pour pratiquer la matière puisque ça utilise une application réelle. Si tu es d'accord, je peux faire une pull request avec l'exercice et les réponses.

**Comment by fuhrmanator** [comment]
J'aime l'idée - cependant, ce n'est pas tout à fait le même problème que modéliser un domaine. Avec la rétroingénierie, les abstractions sont déjà présentes dans la solution. Le jeu Monopoly/Risk a le même problème, car les règles du jeu sont une sorte de solution. Au fait, c'est vraiment difficile quand c'est un domaine qu'on ne connaît pas bien et pour lequel un modèle n'existe pas encore. Ce genre d'exercice est diffficile à faire.

Mais, ça reste un exercice intéressant pour travailler les concepts (classes/attributs/associations) et la communauté étudiante connaît le domaine ce qui est motivant.

**Comment by Olon11** [comment]
Je suis d'accord avec toi. L'objectif de l'exercice, c'est surtout d'appliquer et règle et apprendre à reconnaître un domaine. Je crois que les étudiants ne sont pas encore prêts à modéliser un domaine à partir d'un document de 500 pages sur le code de taxes canadien 😜.
