### ISSUE TITLE
La première phrase du chapitre 4 semble pointer vers le mauvais chapitre (9)

### ISSUE THREAD

**Issue by probitaille** [fuhrmanator/log210-ndc-quarto#123]
La phrase qui semble problématique indique:

> Les MDD sont expliqués en détail dans le chapitre 9 , mais voici des points importants :

Cependant, le chapitre 9 se concentre sur les RDCU sans vraiment donner de détails sur les MDD.

**Comment by fuhrmanator** [comment]
Je mais une capture d'écran, car il y a normalement une icône qui n'est pas copiable (c'est une image dans la version Web):

![image](https://github.com/fuhrmanator/log210-ndc-quarto/assets/7606540/cc18e0e8-2d01-49c8-8c89-9d7204beabcc)

Lorsqu'on voit l'icône avec le livre, on fait référence au livre de Craig Larman (c'est expliqué dans la Note [ici](https://fuhrmanator.github.io/log210-ndc-quarto/#livre-compl%C3%A9mentaire)). Le chapitre 9 de son livre est bel est bien le chapitre sur les MDD.
