### ISSUE TITLE
Chapitre 2: FURPS+ vs ISO 25010:2011

### ISSUE THREAD

**Issue by probitaille** [fuhrmanator/log210-ndc-quarto#124]
Au chapitre 2, pour toutes les exigences non fonctionnelles, je propose plutôt de se référer à la norme [ISO 2501:2011](https://www.iso.org/obp/ui/#iso:std:iso-iec:25010:ed-1:v1:en) qui définit 8 caractéristiques de qualité et des sous-caractéristiques pour les produits logiciels.

1. Adéquation fonctionnelle (Functional suitability)
1.1 Complétude fonctionnelle (Functional completeness)
1.2 Exactitude fonctionnelle (Functional correctness)
1.3 Pertinence fonctionnelle (Functional appropriateness)
2. Efficacité de performance (Performance efficiency)
2.1 Comportement temporel (Time behavior)
2.2 Utilisation des ressources (Resource utilization)
2.3 Capacité (Capacity)
3. Compatibilité (Compatibility)
3.1 Interopérabilité (Interoperability)
3.2 Coexistence (Coexistence)
4. Utilisabilité (Usability)
4.1 Reconnaissabilité (Appropriatness recognizability)
4.2 Facilité d'apprentissage (learnability)
4.3 Opérabilité (Operability)
4.4 Protection contre les erreurs utilisateur (User error protection)
4.5 Esthétique de l'interface utilisateur (User interface aesthetics)
4.6 Accessibilité (accessibility)
5. Fiabilité (Reliability)
5.1 Maturité (Maturity)
5.2 Disponibilité (Availability)
5.3 Tolérance aux erreurs (Fault tolerance)
5.4 Récupérabilité (Recoverability)
6. Sécurité
6.1 Confidentialité (Confidentiality)
6.2 Intégrité (Integrity)
6.3 Non-Répudiation (Non-repudiation)
6.4 Authenticité (Authenticity)
6.5 Responsabilité (Accountability)
7. Maintenabilité
7.1 Modularité (Modularity)
7.2 Réutilisabilité (Reusability)
7.3 Analysabilité (Analysability)
7.4 Modifiabilité (Modifiability)
7.5 Testabilité (Testability)
8. Portabilité
8.1 Adaptabilité (Adaptability)
8.2 Installabilité (Installability)
8.3 Remplaçabilité (Replaceability)

En bref, cela me semble plus à jour et mieux reconnu que FURPS+. C'est aussi ce qui est présenté dans le cours LOG410.

**Comment by fuhrmanator** [comment]
Je suis en faveur d'ajouter la référence ISO-2501:2011, mais j'aime garder FURPS+ pour sa simplicité (qui est suffisante pour LOG210) bien que ce soit un peu vieux. 

Merci pour toutes les traductions en français -- si ça te tente, tu peux faire une Pull Request avec le changement.

**Comment by probitaille** [comment]
En étudiant la norme, j'ai découvert qu'il y a eu une mise à jour récente à ISO/IEC 25010:2023. J'ai pris en compte les modifications des caractérisiques par rapport à mon premier commentaire dans mon Pull Request.
