### ISSUE TITLE
Définir ce qu'est une classe conceptuelle

### ISSUE THREAD

**Issue by fuhrmanator** [fuhrmanator/log210-ndc-quarto#129]
Le chapitre sur les MDD ne contient aucune définition de ce qu'est une classe conceptuelle.

**Comment by probitaille** [comment]
Il peut être utile aussi de rappeler le concept de « super-classe conception » (Larman, chapitre F26.5) et de « classe conceptuelle abstraites ». (Larman, chapitre F26.7)
