### ISSUE TITLE
Exercice pour les verbes plus riches sur les associations dans les MDD

### ISSUE THREAD

**Issue by fuhrmanator** [fuhrmanator/log210-ndc-quarto#39]
MDD.qmd a le conseil suivant:

> - Des verbes simples comme "A", "Utilise", "Possède", "Contient", etc. sont généralement des choix médiocres, car ils n'aident pas notre compréhension du domaine. Essayez de trouver des verbes plus riches, si possible.

Un exercice réaliste à ce propos pourrait être utile.

**Comment by Olon11** [comment]
Veux-tu que je m'en occupe?

**Comment by fuhrmanator** [comment]
Vas-y, si on a plus d'exercice avant la remise de la fabriqueREL, tant mieux!

**Comment by fuhrmanator** [comment]
Fixed in #112
