### ISSUE TITLE
Dans la section prérequis, les noms des membres de Gang Of Four sont répétés 2 fois

### ISSUE THREAD

**Issue by Olon11** [fuhrmanator/log210-ndc-quarto#41]
Le texte est :

> l’application des patterns de conception de la « Bande des quatre » (Gang of Four) : Gamma, Helm, Johnson et Vlissides Gamma, Helm, Johnson, & Vlissides ([1994](https://fuhrmanator.github.io/log210-ndc-quarto/references.html#ref-GoF1994)).

Le texte devrait être : 

> l’application des patterns de conception de la « Bande des quatre » (Gang of Four) : Gamma, Helm, Johnson et Vlissides ([1994](https://fuhrmanator.github.io/log210-ndc-quarto/references.html#ref-GoF1994)).

**Comment by fuhrmanator** [comment]
Comme larman Utilise "patterns" je normalise partout (ou on essaie...). Donc je supprime "de conception"
