### ISSUE TITLE
Qualité du français

### ISSUE THREAD

**Issue by Olon11** [fuhrmanator/log210-ndc-quarto#43]
Cet issue permet de lister les fautes ou les améliorations en lien avec le français, plutôt que de faire une issue par faute.

# Section 1

## Section 1.3

- [x] trie de Shell -> tri de Shell

### Section 1.3.2

- [x] Le texte « (aussi appelée accidentelle) » devrait être à la fin de la première phrase plutôt qu'à la quatrième phrase.

# Section 3

### Section 3.1.2

- [x] À la dernière phrase de la section, Larman est écrit 2 fois

# Section 4

### Section 4.1.1

- [x] Qui sont les parties -> Quelles sont les parties

## Section 4.3

- [x] par des lignes entre classes -> par des lignes entre les classes

# Section 6

- [x] Principes pour déterminer Où Mettre une Méthode -> Principes pour déterminer où mettre une méthode
- [x] vous devez décider souvent où placer une méthode (dans quelle classe), et cette décision -> vous devez souvent décider dans quelle classe placer une méthode et cette décision

## Section 6.1

- [x] lors duquel, vous ne feriez pas un logiciel avec 10 patterns GoF, vous ne feriez pas non plus les diagrammes UML -> lors duquel vous ne feriez pas un logiciel avec 10 patrons GoF ou de diagrammes UML
- [x] Cette négligence à la conception -> Cette négligence de la conception

## Section 6.4

- [x] patterns GoF -> patrons GoF (cette faute est présente trois fois dans la section)

# Section 9

## Section 9.3

- [x] Si un objet A veut envoyé -> Si un objet A veut envoyer

## Section 9.4

- [x] pattern -> patron
- [x] un idiome -> une méthode (un idiome est un instrument de communication linguistique)

## Section 9.7

- [x] car ces patterns ajoutent souvent -> car ces patrons ajoutent souvent

## Section 9.8

- [x] Pattern « Faire soi-même » -> Patron « Faire soi-même » (cette faute est présente deux fois dans la section)

## Section 9.9

- [x] Vous y trouverez également des artefacts -> Vous y trouverez également des artéfacts
- [x] Considérez les deux artefacts -> Considérez les deux artéfacts
- [x] Comparez ces deux artefacts -> Comparez ces deux artéfacts

# Section 10

- [x] beaucoup de temps, et l’équipe -> beaucoup de temps et l’équipe
- [x] pour les fonctionnalités, et le développement -> pour les fonctionnalités et le développement
- [x] un test qui appelle à une fonction -> un test qui appelle une fonction
- [x] et une valeur de retour même. -> et une valeur de retour.
- [x] Une personne pure et dure du TDD -> Un adepte pur et dur du TDD
- [x] Sachez qu’il existe beaucoup d’cadriciels -> Sachez qu’il existe beaucoup de cadriciels 

## Section 10.1

- [x] par Dave Thomas, et le but -> par Dave Thomas et le but
- [x] lieu du nombre et, pour les multiples -> lieu du nombre et pour les multiples
- [x] un framework de test -> un cadriciel de test

# Section 12

## Section 12.1

- [x] il s’agit d’insécurité, et c’est tout à fait normal -> il s’agit d’insécurité et c’est tout à fait normal

## Section 12.4

- [x] Une personne à l’équipe -> Une personne de l’équipe

# Section 14

- [x] patterns GoF -> patrons GoF (cette faute est présente plusieurs fois dans la section)

# Section 15

- [x] (ou l’utilisation des patterns) -> (ou l’utilisation des patrons)

# Section 17

- [x] et est fait en PlantUML -> et est faite en PlantUML
- [x] alors le système est prêt pour accepter d’autres actions -> alors le système est prêt à accepter d’autres actions

# Section 18

- [x] de namespace existe. -> de namespace (espace de nom) existe.

# Section 20

- [x] les points pour les fonctionnalités réussites ne compte  -> les points pour les fonctionnalités réussies ne comptent
- [x] réduction de la facilité de faire du plagiat -> difficulté à faire du plagiat
- [x] cours, et las éléments d’analyse -> cours et les éléments d’analyse
- [x] proactif et pret à confronter -> proactif et prêt à confronter
- [x] patterns -> patrons

## Section 20.4

- [x] est libre à modifier -> est libre de modifier
- [x] tous les cas synchronisation -> tous les cas de synchronisation
- [x] pas très intéressant -> inintéressant (pas une faute, mais une suggestion d'amélioration)

# Annexes

- [x] Appendix -> Annexe ou Appendice (selon la nécessité de la section, voir note ci-bas)

Selon le guide de rédaction de l'ÉTS :

> Contrairement aux annexes, les appendices sont considérés comme un supplément
d’information et ils ne sont pas jugés essentiels à la compréhension du document, mais il peut
être intéressant de les joindre au document.

# Toutes les sections

## Écriture épicène

- [x] Uniformiser le style de l'écriture épicène. Parfois, on utilise les parenthèses (ex.: étudiant(e)) et parfois, on écrit les deux mots au long (ex.: ingénieure ou ingénieur). Le guide d'écriture inclusive de l'ÉTS recommande d'écrire les deux mots au long.

**Comment by fuhrmanator** [comment]
" Qui sont les parties -> Quelles sont les parties" -- non, Caissier, Client, Joueur, etc. sont les qui

"patrons GoF" -- on garde "patterns" partout, comme Larman en français

"idome" est bien utilisé en français dans Larman à plusieurs endroits.

"artefact" sans accent n'est pas faux

"beaucoup de temps, et l’équipe -> beaucoup de temps et l’équipe" -- c'est la réviseure qui a changé - c'est un choix de style?

" Une personne pure et dure du TDD -> Un adepte pur et dur du TDD" -- on laisse pour langage inclusif (?)

"réduction de la facilité de faire du plagiat -> difficulté à faire du plagiat" -- est-ce que ça change le sens? j'espère qu'il sera difficile, mais je ne sais pas. Il est moins facile.

La 2e révision par la réviseure suivait les directives du (nouveau) Guide d'écriture inclusive de l'ÉTS
