### ISSUE TITLE
Dans certaines sections, lorsqu'on référence le livre de Larman, il manque l'icône du livre

### ISSUE THREAD

**Issue by Olon11** [fuhrmanator/log210-ndc-quarto#44]
Section 2.1 et la référence vers la section 5.4 du livre de Larman.

**Comment by Olon11** [comment]
Idem pour la section 3 et la référence vers le chapitre 6.

**Comment by Olon11** [comment]
Idem pour la section 11.3 et la référence vers les chapitres F19.2/A22.2.

**Comment by Olon11** [comment]
Idem pour la section 15 et la référence vers les chapitres A36.3/F30.3.

**Comment by fuhrmanator** [comment]
Je ferai un gros find/replace avec expression régulière.

**Comment by fuhrmanator** [comment]
J'ai remarqué aussi que parfois l'ordre des références est A/F plutôt que F/A, alors j'en profite pour normaliser ça aussi.
