### ISSUE TITLE
Détailler la section 3.1.1 Scénario : Attaquer un pays

### ISSUE THREAD

**Issue by Olon11** [fuhrmanator/log210-ndc-quarto#45]
Dans le cas d'utilisation, devrait-on mentionner le nombre maximal de régiments que peuvent choisir le Joueur attaquant (max. 3) et le Joueur défenseur (max. 2) ?

Aussi, serait-il pertinent de mentionner la contrainte « un régiment au moins doit rester libre d’engagements sur le territoire attaquant » ?

À l'étape 4 du cas d'utilisation, je suggère plutôt d'écrire « Les deux Joueurs jettent un dé par régiment qu'ils ont engagé aux étapes précédentes. »

À l'étape 5, serait-il pertinent d'expliciter les règles de comparaison des règles?

**Comment by fuhrmanator** [comment]
J'hésite avec un exemple trop compliqué - le but est de comprendre la méthodologie. Peut-être suffit-il d'écrire que ce scénario est une simplification pour faciliter la compréhension, mais le cas réel comporte plus de détails qu'il faudra considérer. 

On pourrait en faire un exercice (un contrat, RDCU, etc.) avec tous les détails. Je ne pense pas avoir le temps pour compléter avant le délai pour la fabriqueREL.

**Comment by Olon11** [comment]
> Peut-être suffit-il d'écrire que ce scénario est une simplification pour faciliter la compréhension

Je crois que ça serait une bonne idée.

> On pourrait en faire un exercice

Oui, ce pourrait être un objectif futur.

**Comment by fuhrmanator** [comment]
J'intègre l'idée dans l'exercice pour `terminerAttaque()` qui existe déjà.
