### ISSUE TITLE
4.5 Attributs dérivés devrait arriver avant l'exemple 4.4

### ISSUE THREAD

**Issue by Olon11** [fuhrmanator/log210-ndc-quarto#46]
Dans le livre de Larman, on voyait les attributs calculés. S'ils sont encore vus en classe, ce serait pertinent de les présenter. L'attribut calculé est précédé par `/` pour montrer que c'est un attribut qui est calculé à partir d'autres attributs.

Ex. avec le jeu de dés :

```plantuml
class Joueur {
    nom:String
    nbLancers:int
    nbLancersGagnés:int
    / ratioPartiesGagnées:float
}
```

Dans le code, on aurait alors :

```javascript
class Joueur {
    - nom:String
    - nbLancers:number
    - nbLancersGagnes:number
    
    public number ratioPartiesGagnees() {
        return this.nbLancersGagnes / this.nbLancers;
    }
}
```

**Comment by Olon11** [comment]
D'ailleurs, un attribut calcul est utilisé dans la figure 4.1 (classe Joueur)

**Comment by Olon11** [comment]
Les attributs dérivés sont dans la section 4.5. Ce serait pertinent des les inclure avant la section 4.4.

**Comment by Olon11** [comment]
Idem pour la section 4.7 Classes d'associations. Puisqu'on utilise ce type de classe dans le MDD de la figure 4.1, on devrait présenter la théorie avant la section 4.4.

**Comment by fuhrmanator** [comment]
J'ai toujours compris **dérivé** et **calculé** de la même manière. Larman ne fait pas une différence (au moins, je n'ai pas trouvé ça dans le texte). 

Ton exemple avec le jeu de dé (ratio) n'est pas dans Larman (à ma connaissance). As-tu une référence (section) dans le chapitre 9 de Larman?

**Comment by fuhrmanator** [comment]
> Les attributs dérivés sont dans la section 4.5. Ce serait pertinent des les inclure avant la section 4.4.

Je suis d'accord.

**Comment by Olon11** [comment]
> J'ai toujours compris dérivé et calculé de la même manière

Oui, les termes sont interchangeables. J'aurais dû écrire dérivé pour respecter ce qui est écrit dans les notes de cours. Dans les notes de cours, on pourrait aussi dire que c'est un autre nom pour ce type d'attributs.

> Ton exemple avec le jeu de dé (ratio) n'est pas dans Larman (à ma connaissance).

Effectivement, c'est un exemple inventé à partir du jeu de dés (le squelette de base du laboratoire).
