### ISSUE TITLE
Section 4.4 Exemple de MDD pour le jeu Risk : questionnement sur les règles du Risk

### ISSUE THREAD

**Issue by Olon11** [fuhrmanator/log210-ndc-quarto#47]
Dans la figure 4.1, l'association Continent -->Pays précise qu'un continent peut contenir 4, 6, 7, 9 ou 12 pays. Est-ce une règle du Risk ou une observation basée sur la carte du jeu? Est-ce qu'on pourrait avoir une autre carte avec un continent qui a 10 pays? Dans ce cas, la cardinalité de l'association serait 1 à plusieurs.

**Comment by Olon11** [comment]
Idem pour le nombre de pays et de continents dans le plateau de Risk.

**Comment by fuhrmanator** [comment]
J'ai ajouté une explication https://github.com/fuhrmanator/log210-ndc-quarto/blob/56c8e27ff908b52340c6898d39111562bad893c6/MDD.qmd#L124

**Comment by Olon11** [comment]
Oui, j'avais bien compris ce point. Ma question était plutôt en lien avec la méthodologie. Est-ce que ce serait correct d'avoir une association 1 à plusieurs entre Continent et Pays?

**Comment by fuhrmanator** [comment]
Oui, selon moi c'est correct, mais ça laisse l'impression que c'est variable (dynamique) plutôt que statique.

**Comment by fuhrmanator** [comment]
Larman, dans son exemple de Monopoly, spécifie 40 Cases dans un Plateau, ce n'est pas 1 à plusieurs.
