### ISSUE TITLE
Section 5 : Définir ce qu'est un API

### ISSUE THREAD

**Issue by Olon11** [fuhrmanator/log210-ndc-quarto#50]
La plupart des étudiants n'ont pas beaucoup d'expérience en développement de systèmes, alors je ne crois pas qu'ils savent ce qu'est un API. J'ajouterais une définition ou même une section sur le sujet dans la section 5.

**Comment by Olon11** [comment]
Je pensais à une description plus détaillée avec un exemple. On peut expliquer que l'API est la façon de communiquer avec un système et donner quelques exemples de systèmes (une classe, un logiciel en ligne de commande, un logiciel web, etc.).

**Comment by fuhrmanator** [comment]
OK - j'attends un PR de ta part ;-)

**Comment by Olon11** [comment]
Je vois deux sections candidates pour ce texte. À la fin de la section 1 ou au début de la section 5. Qu'est-ce que tu préfères?

**Comment by fuhrmanator** [comment]
Ça dépend du texte - section 1 est l'introduction (donc devrait être plus superficiel) tandis que 5 est carrément les DSS et peut être détaillé.

**Comment by Olon11** [comment]
Je vais écrire le texte et on verra après.

**Comment by fuhrmanator** [comment]
fixed by #106
