### ISSUE TITLE
Prise de contrôle d'un pays (cas d'utilisation de la section 3.1.1)

### ISSUE THREAD

**Issue by Olon11** [fuhrmanator/log210-ndc-quarto#51]
On fait référence au fait qu'un pays puisse changer de main dans la section 5.3, alors ce serait bien que ce soit noté dans le cas d'utilisation.

**Comment by fuhrmanator** [comment]
Je cherche ces conditions sur la page à https://fr.wikipedia.org/wiki/Risk#Attaques mais je n'ai rien trouvé. 

Je connais mal Risk :( J'ai trouvé ceci sur la page en anglais : https://en.wikipedia.org/wiki/Risk_(game)#Gameplay

> When attacking, a battle may continue until the attacker decides to stop attacking, the attacker has no more armies with which to attack, or the defender has lost their last army at the defending territory, **at which point the attacker takes over the territory by moving armies onto it and draws a territory card for that turn**.

On pourrait modifier le texte du passage Wikipedia pour ajouter entre crochets [ ] la traduction de la partie en gras ci-haut.

Après, on modifie le cas d'utilisation.

**Comment by fuhrmanator** [comment]
Fixed in #92 (j'ai ajouté une note pour dire qu'on en fait abstraction)

**Comment by fuhrmanator** [comment]
Je n'aime pas tout à fait... on devrait expliquer ce qui se passe après la boucle dans le cas d'utilisation.

**Comment by Olon11** [comment]
Je suis d'accord 👍
