### ISSUE TITLE
Définir scénario alternatif (cas d'utilisation)

### ISSUE THREAD

**Issue by Olon11** [fuhrmanator/log210-ndc-quarto#52]
Il faudrait ajouter une description et un exemple de scénario alternatif dans la section 3. Ce serait aussi utile d'ajouter un exemple de DSS pour ce scénario alternatif dans la section 5.

**Comment by fuhrmanator** [comment]
Je vais ajouter une section dans le chapitre 3 et y faire référence dans la FAQ.

**Comment by fuhrmanator** [comment]
![image](https://user-images.githubusercontent.com/7606540/217922093-fee62020-1b65-47fb-a1d1-b450c90cd10b.png)

**Comment by Olon11** [comment]
Je suis d'accord!
