### ISSUE TITLE
Préciser la réponse à la FAQ DSS beaucoup d'arguments (section 5.3.3)

### ISSUE THREAD

**Issue by Olon11** [fuhrmanator/log210-ndc-quarto#53]
Est-ce que c'est correct d'avoir beaucoup de paramètres dans mon DSS?
Est-ce que le fait d'utiliser un objet dans le code impacte mon DSS? (Je sais que non, mais un étudiant se posera probablement la question)
Est-ce que l'objet de paramètre est juste une façon de simplifier mon implémentation?

**Comment by fuhrmanator** [comment]
Je ferai un petit résumé pour répondre à ces questions.

**Comment by Olon11** [comment]
Très bien! Il faudrait préciser ce point :

> Est-ce que le fait d'utiliser un objet dans le code impacte mon DSS?

À bien y penser, j'ajouterais un rappel (ça peut juste être une phrase) sur pourquoi on ne veut pas que la couche présentation aie accès à la couche domaine.

**Comment by fuhrmanator** [comment]
Il y a déjà "ça empiète sur les responsabilités" --- ça ne suffit pas?

**Comment by Olon11** [comment]
Je ne suis pas certain qu'un étudiant comprendrait pourquoi. On ne veux pas que ce soit un dogme, alors il faut expliquer la raison derrière.

**Comment by fuhrmanator** [comment]
Le problème que tu mentionnes est plus par rapport à la raison de séparer les couches. Devrions-nous avoir une autre FAQ?

> Pourquoi séparer les couches présentation et domaine? 

Ça me fait penser à cette présentation, qui n'a jamais été intégré dans le manuel: https://log210-cfuhrman.github.io/log210-valider-architecture-couches/#/

**Comment by Olon11** [comment]
> Devrions-nous avoir une autre FAQ?

Ça serait une bonne idée.

> Ça me fait penser à cette présentation...

C'est une bonne présentation pour expliquer comment les diagrammes sont utilisés dans le code. Elle explique aussi pourquoi on veut la sépartion des couches. En bref, on sépare les couches, parce que :

- on veut améliorer la cohésion du domaine
- on veut réduire le couplage entre la couche présentation et la couche domaine
- la couche présentation évolue plus rapidement que la couche domaine
- il peut y avoir plusieurs couches de présentation (ex.: site web, app mobile)
- on veut ouvrir l'API à des systèmes externes
- on veut améliorer la réutilisation du code pour appeler la même API à plusieurs endroits dans le code (patron commande) ou dans un autre projet
- c'est plus simple à tester (en lien avec le point 1 et 2)
- c'est moins long à implémenter et modifier (en lien avec le point 1 et 2)
- ça rend l'application plus simple à comprendre (ex.: pour les nouveaux développeurs) (en lien avec le point 1 et 2)

Avec les figures et les exemples de code de la présentation, ce serait clair et complet.
