### ISSUE TITLE
FAQ passer l'objet `<body>` (Section 5.3.4)

### ISSUE THREAD

**Issue by Olon11** [fuhrmanator/log210-ndc-quarto#54]
Dans la section 5.3.4, on dit :

> Décortiquer toutes les informations dans un formulaire Web est compliqué

Cette prémisse est fausse, car le site web s'occupe de tout décortiquer le formulaire pour le développeur. Même pas besoin de JavaScript, juste utiliser les balises `input` et `form` correctement. Je n'ai jamais entendu quelqu'un dire que c'était compliqué.

On pourrait dire que c'est compliqué de transformer les arguments primitifs en objets du domaine et qu'on veut passer les objets du domaine entre la couche présentation et la couche domaine pour simplifier. Ce serait plus juste et l'explication reste la même.

**Comment by fuhrmanator** [comment]
> On pourrait dire que c'est compliqué de transformer les arguments primitifs en objets du domaine et qu'on veut passer les objets du domaine entre la couche présentation et la couche domaine pour simplifier. Ce serait plus juste et l'explication reste la même.

Je ne comprends plus le sens. Je me souviens qu'il y avait des solutions remarquables avec un élément `<body>` passé au contrôleur pour trouver des informations. 

Avec ta nouvelle proposition plus haut, je ne vois pas l'utilité de passer le `<body>`. Peut-être que le problème a-t-il deux dimensions (incompétence avec input/form et séparation des couches)? Je ne suis pas sûr que la personne savait "transformer les arguments primitifs en objets". Elle a vu qu'on saisit des infos dans une page (GUI) et le contrôleur les consomme après.

Je propose:
> Si le contrôleur GRASP a besoin des informations présentes dans le formulaire Web, pourquoi ne pas passer l'objet `<body>` de la page Web directement au contrôleur GRASP et de le laisser en extraire l'information? 

(STP vérifier mon français)

C'est important de savoir ce que sont des fausses idées (misconceptions), même quand c'est farfelu.

**Comment by Olon11** [comment]
> Peut-être que le problème a-t-il deux dimensions (incompétence avec input/form et séparation des couches)?

Tu as raison. Le fait de passer le corps de la page HTML est un problème relié à la maîtrise du HTML. Je crois que la personne ne savait pas comment les formulaires HTML marchaient et c'est pour ça qu'elle a fait cela.

C'est différent du problème que je soulève. Aucune personne qui comprend le fonctionnement des formulaires HMTL ne passerait le corps de la page au serveur. Par contre, on pourrait penser que c'est plus facile de passer des objets du domaine que des valeurs primitives. Dans ce cas, ce serait un problème lié à la séparation des couches.

> Si le contrôleur GRASP a besoin des informations présentes dans le formulaire Web, pourquoi ne pas passer l'objet <body> de la page Web directement au contrôleur GRASP et de le laisser en extraire l'information?
> (STP vérifier mon français)
> C'est important de savoir ce que sont des fausses idées (misconceptions), même quand c'est farfelu.

Le français est correct. Par contre, même si ça clarifie le texte, je crois que ça ne règle pas le problème que j'ai soulevé. On pourrait ajouter (en plus du body) « pourquoi ne pas passer les objets du modèle à la couche de présentation et vice versa ». Il faut dire que même si dans un application web, on ne peut pas faire cela facilement, c'est très facile et tentant de le faire dans une application graphique avec Java Swing ou Qt puisque le modèle et la couche présentation utilisent le même langage (et ne sont pas séparés par un serveur). Ça permettrait d'appliquer cette FAQ à plus de cas.

**Comment by fuhrmanator** [comment]
> « pourquoi ne pas passer les objets du modèle à la couche de présentation et vice versa »

Si je comprends bien, c'est une autre question. Moi-même j'ai fait cette erreur (je crois que c'était dans le squelette même). Je crée un autre issue pour cela.
