### ISSUE TITLE
Le lien dans le section 6.1 n'existe plus

### ISSUE THREAD

**Issue by Olon11** [fuhrmanator/log210-ndc-quarto#55]
Le lien suivant est à remplacer : https://www.ibm.com/developerworks/library/j-eaed1/

La page est archivée : https://web.archive.org/web/20161029141308/http://www.ibm.com/developerworks/library/j-eaed1/

L'article en PDF est archivé : https://web.archive.org/web/20160316155349/http://www.ibm.com/developerworks/library/j-eaed1/j-eaed1-pdf.pdf

**Comment by fuhrmanator** [comment]
Merci d'avoir trouvé ça avec archive.org

**Comment by Olon11** [comment]
Le lien dans la bibliographie a été changé, mais le lien au début de la section n'a pas été mis à jour

<img width="296" alt="image" src="https://user-images.githubusercontent.com/15785239/218286974-ffdbe57b-c1b5-414b-9ea5-340dd9a30f17.png">

**Comment by fuhrmanator** [comment]
Ha - ton issue n'était pas super clair :-/ OK, merci je corrige.
