### ISSUE TITLE
Patrons GRASP créateur et contrôleur

### ISSUE THREAD

**Issue by Olon11** [fuhrmanator/log210-ndc-quarto#56]
Est-ce que les critères de ces patrons sont en ordre de priorité? Si oui, le mentionner.

**Comment by fuhrmanator** [comment]
J'ai besoin de plus de contexte, p.ex. la section? la page dans le PDF? Quels critères?

**Comment by Olon11** [comment]
Dans le tableau 6.1

![image](https://user-images.githubusercontent.com/15785239/215850107-e009ce60-147c-42db-847a-bd3e021f81a7.png)

**Comment by fuhrmanator** [comment]
C'est un extrait du tableau - il n'y a pas de priorité.


L'heuristique pour favoriser l'agrégation (Créateur 1, 2) revient plus tard dans les RDCU: https://fuhrmanator.github.io/log210-ndc-quarto/RDCU.html#cr%C3%A9er-une-instance

Est-ce OK pour fermer?

**Comment by Olon11** [comment]
S'il n'y a pas de priorité, les étudiants pourraient choisir n'importe quel condition. Pourtant, dans la section sur le RDCU, on dit qu'il faut favoriser l'agrégation. Il y a donc une priorité. Je crois qu'il faut adresser cela dans le tableau des GRASP.

**Comment by fuhrmanator** [comment]
OK, j'ajoute qqch comme `[à favoriser]` (avec crochets pour indiquer que ce n'est pas dans le texte cité de Larman) pour les Créateur 2. Modifier ce tableau est pénible parce qu'il s'agit d'un https://quarto.org/docs/authoring/tables.html#grid-tables
