### ISSUE TITLE
Reformulation des définitions du patron Contrôleur

### ISSUE THREAD

**Issue by Olon11** [fuhrmanator/log210-ndc-quarto#57]
Pour plus de clarté, je suggère la formulation suivante :

1. Contrôleur de façade : représente le système global, un « objet racine », un équipement ou un sous-système.
2. Contrôleur de session (de cas d’utilisation) : représente un scénario de cas d’utilisation dans lequel l’opération système se produit. On le nomme GestionnaireX, où X est le nom du cas d’utilisation.

**Comment by fuhrmanator** [comment]
Est-ce que tu veux changer les définitions proposées par Larman dans le tableau à la section 6.2? 
![image](https://user-images.githubusercontent.com/7606540/215817990-5ebe5b4f-e3e6-4475-b804-bba3a8fd20a4.png)

**Comment by fuhrmanator** [comment]
Je suis d'accord que c'est plus clair. Cependant, j'ai repris exactement les définitions de la version française du livre Dans 6.2. 

Il faudra expliquer les changements et c'est plus compliqué à présenter le tout.

Je crois qu'il serait acceptable d'écrire entre crochets (lorsqu'un texte a été changé) juste les noms au début:

> 1. [**Contrôleur de façade**] [La classe] représente...
> 2. [**Controleur de sesseion (de cas d'utilisation)**] [La classe] représente... 

Sinon, on peut mettre en gras les noms des contrôleurs dans la définition actuelle.

**Comment by Olon11** [comment]
Ok. Je ne savais pas que c'était ce qui était écrit dans le livre de Larman.

> on peut mettre en gras les noms des contrôleurs dans la définition actuelle.

Ça me semble un compromis acceptable.
