### ISSUE TITLE
La section 7 Dette technique est dans un endroit bizarre dans les notes de cours

### ISSUE THREAD

**Issue by Olon11** [fuhrmanator/log210-ndc-quarto#60]
La section est milieu de la méthodologie de Larman (MDD, DSS, Contrats et RDCU). Ça serait plus logique de la mettre avant le réusinage. Avec cet ordre, on sait maintenant ce qu'est la dette technique et ont apprend comment la résoudre dans le chapitre suivant.

**Comment by fuhrmanator** [comment]
J'ai gardé ce problème pour la fin, car il risque de changer les numéros des chapitres éventuellement.

> La section est [au] milieu de la méthodologie de Larman (MDD, DSS, Contrats et RDCU). 

Oui, je trouve qu'il est important de présenter ça avant les RDCU, car la première colonne du tableau 7.1 «On n’a pas le temps pour la conception !» et "C'est quoi la séparation en couches?" sont des cas où on s'endette et c'est imprudent. 

En plus, puisque le ch. sur GRASP présente le spectre de la conception (et on explique que le hacking cowboy est une négligence de la conception --> dette technique), je trouve que présenter la dette technique juste après est logique.

> Ça serait plus logique de la mettre avant le réusinage. 
> Avec cet ordre, on sait maintenant ce qu'est la dette technique et ont apprend comment la résoudre dans le chapitre suivant.

Je suppose que tu veux dire *juste avant* (car il est déjà avant le réusinage).

**Comment by Olon11** [comment]
> Je suppose que tu veux dire juste avant (car il est déjà avant le réusinage).

Oui!

**Comment by fuhrmanator** [comment]
Je voudrais fermer ce billet (pour avancer) - probablement il y a une meilleure ordre de toute la matière. Dans les balises éditoriales on mention que chaque chapitre devrait être indépendant des autres. Peut-être serait-il mieux de mettre le Spectre de la conception, la Dette Technique et le Réusinage dans des chapitres séparés (ou un même chapitre), plus au début du manuel. Il est trop tard pour faire ça avant la remise pour la fabriqueREL.

**Comment by Olon11** [comment]
Pas de problème. Tu pourras adresser ce problème (ou pas) plus tard.
