### ISSUE TITLE
Commentaires sur la section 8.2 Exemple : Contrats d’opération pour Attaquer un pays

### ISSUE THREAD

**Issue by Olon11** [fuhrmanator/log210-ndc-quarto#61]
Dans la première post-condition de l'opération `annoncerDéfense(nbRégimentsDéfendant:int)`, on devrait lire `a.nbDéfenseurs` plutôt que `a.nbDéfendant` pour être cohérent avec le MDD.

Dans les postconditions, l'instance de Occupation n'est jamais créée.

Dans le diagramme d'objet de la deuxième partie de la figure 8.2, l'assignation des valeurs aux propriétés se fait à l'aide du égal (`=`). Ex.: `nbAttaquant = nbRégimentsAttaquant`.

**Comment by fuhrmanator** [comment]
> Dans la première post-condition de l'opération `annoncerDéfense(nbRégimentsDéfendant:int)`, on devrait lire `a.nbDéfenseurs` plutôt que `a.nbDéfendant` pour être cohérent avec le MDD.

OK - c'est aussi dans la 2e partie de la figure. 

> Dans les postconditions, l'instance de Occupation n'est jamais créée.

Cette instance existe déjà, vu que tous les territoires sont occupés dès el début du jeu (si je comprends bien le jeu!). Est-ce que je me trompe?

> Dans le diagramme d'objet de la deuxième partie de la figure 8.2, l'assignation des valeurs aux propriétés se fait à l'aide du égal (`=`). Ex.: `nbAttaquant = nbRégimentsAttaquant`.

Oops. Merci. Je corrige ça.

**Comment by Olon11** [comment]
> Cette instance existe déjà, vu que tous les territoires sont occupés dès el début du jeu (si je comprends bien le jeu!). Est-ce que je me trompe?

J'ai vérifié et c'est le cas.
