### ISSUE TITLE
Relier davantage le chapitre RDCU à la méthodologie globale

### ISSUE THREAD

**Issue by Olon11** [fuhrmanator/log210-ndc-quarto#64]
Au début de la section 9, j'ajouterais que la RDCU vise à concevoir une solution pour une opération d'un DSS. Ce point devrait aussi être adressé entre la section 9.1 et la section 9.2. Beaucoup d'étudiants ont de la difficulté à faire des liens entre les diagrammes. Il faut renforcer le fait que tous le processus de conception est une suite logique.

Dans la liste suivante : « De manière générale, toute bonne RDCU doit faire les choses suivantes », j'ajouterais le point suivant :

- Faire usage des classes conceptuelles du MDD et respecter leurs associations et cardinalités

**Comment by fuhrmanator** [comment]
> * Faire usage des classes conceptuelles du MDD et respecter leurs associations et cardinalités

On a déjà le point pour satisfaire les postconditions du contrat d'opération. Je me demande si ton point est redondant, car les postconditions sont déjà écrites selon les contraintes du MDD.

**Comment by fuhrmanator** [comment]
Sinon, j'ai toujours aimé la figure F17.3/A18.3 dans le livre de Larman parce qu'on voit quasiment le DSS qui se détaille (comme si zoomait à l'intérieur de l'objet :Système):

![image](https://user-images.githubusercontent.com/7606540/217964378-5df1fcff-4ba9-42f7-9266-4fbab68e579d.png)

Penses-tu que ce genre d'explication ou de visualisation rejoint ton premier point?

**Comment by Olon11** [comment]
> On a déjà le point pour satisfaire les postconditions du contrat d'opération. Je me demande si ton point est redondant, car les postconditions sont déjà écrites selon les contraintes du MDD.

C'est vrai, mais il n'y a pas que les postconditions à représenter dans la RDCU. On peut respecter les postconditions sans respecter le MDD. Je crois que c'est bon de le rappeler. Je demande des diagrammes de séquence dans GTI311 et les étudiants ont de la difficulté avec ce point. Ils inventent souvent des associations, des méthodes ou des propriétés qui ne sont pas dans le diagramme de classes.

> Sinon, j'ai toujours aimé la figure F17.3/A18.3 dans le livre de Larman parce qu'on voit quasiment le DSS qui se détaille (comme si zoomait à l'intérieur de l'objet :Système):

Ça serait intéressant d'avoir cela. Un RDCU fait étape par étape. On part de la fin (le retour du DSS) et on veut se rendre au début (paramètres du DSS) en respectant le MDD et les postconditions du contrat. C'est peut-être plus approprié dans le cours, par contre.

**Comment by fuhrmanator** [comment]
> Ça serait intéressant d'avoir cela. Un RDCU fait étape par étape.

C'est au fait la solution à l'exercice "Ouvrir la caisse" que nous n'avons pas (encore) rendu disponible. Il s'agit de #68.
