### ISSUE TITLE
Dans les sections 9.2.1, 9.2.2 et 9.2.3, il manque les références.

### ISSUE THREAD

**Issue by Olon11** [fuhrmanator/log210-ndc-quarto#65]
C'est écrit : « Référez-vous à la définition dans le . ». Le quoi?

**Comment by Olon11** [comment]
Idem dans la section 9.2.2. « former une association est GRASP Expert, défini dans le . »

**Comment by Olon11** [comment]
Section 9.2.3 : « Il suffit de suivre le principe GRASP Expert, défini dans le . »

**Comment by fuhrmanator** [comment]
Je crois qu'il s'agit d'un bogue dans Quarto pour le site web. Dans la version PDF c'est:
![image](https://user-images.githubusercontent.com/7606540/215811176-3ebfa9ff-f56d-4838-aa21-6efe50277cd7.png)

**Comment by fuhrmanator** [comment]
Voici le HTML:
![image](https://user-images.githubusercontent.com/7606540/215811967-90266bb7-ce9a-4d88-aab2-dfb4f55b8765.png)

**Comment by fuhrmanator** [comment]
Il s'agit d'une utilisation d'étiquette qui ne fonctionne que dans LaTeX (le PDF). `\namere{...}` -- on doit supprimer ça partout et remplacer par les `@etiquette` qui sont la syntaxe Quarto. Malheureusement, ça ne permet pas de faire des liens aux définitions précises dans le tableau (Quarto ne supporte pas la définition d'étiquette arbitraire, c'est uniquement dans une section, figure, tableau, exercice, etc.). J'ai créé une discussion à  https://github.com/quarto-dev/quarto-cli/discussions/4170
