### ISSUE TITLE
Dans l'exercice 3 de la section 9.9, expliquer qu'un cornet sert à brasser plusieurs dés en même temps

### ISSUE THREAD

**Issue by Olon11** [fuhrmanator/log210-ndc-quarto#66]
Ce n'est pas un terme qu'on utilise régulièrement et rien ne sort sur Google.

**Comment by fuhrmanator** [comment]
Antidote me trouve ceci:
> suisse – Contenant
> cornet à dés
> Gobelet dans lequel on agite les dés à jouer.
> dice cup

Mais je suis d'accord avec la remarque. On pourrait remplacer par Gobelet pour faciliter.

**Comment by Olon11** [comment]
Il y a une faute de français : à dès -> à dés
