### ISSUE TITLE
Modèles du domaine de Monopoly de la section 9.9

### ISSUE THREAD

**Issue by Olon11** [fuhrmanator/log210-ndc-quarto#67]
Les modèles du domaine devraient être des figures (9.10 et 9.11).

Il manque les types pour les attributs des MDD.

**Comment by fuhrmanator** [comment]
Les numéros de figures ont été rajoutés dans #72.

Pour les types d'attributs :

- Il n'y en a pas dans la figure de Larman. 
- Le fait d'avoir un MDD incomplet rend plus "ouvert" l'exercice de critique de conception. C'est l'intention pédagogique. Cet exercice se trouve au niveau le plus haut de la [taxonomie de Bloom](https://fr.wikipedia.org/wiki/Taxonomie_de_Bloom#Composition).
