### ISSUE TITLE
Suggestions d'améliorations à la section 14.2

### ISSUE THREAD

**Issue by Olon11** [fuhrmanator/log210-ndc-quarto#78]
Pour bien définir le problème, il faut expliquer pourquoi on voudrait utiliser plusieurs calculateurs de taxes. Je ne connais pas le domaine des calculateurs de taxes, mais j'imagine que certains calculateurs ne supportent pas toutes les régions (ex.: un multinationale avec un seul système POS) ou les produits.

Pour faire des liens avec les 6 critères de qualité des classes (les 6C) présentés en LOG121, je reformulerais la section suivante :

> Ça nuirait à la lisibilité du code, et la méthode qui contient tout ce code deviendrait de plus en plus longue. Même si l’on faisait une méthode pour encapsuler le code de chaque branche, ça ferait toujours augmenter les responsabilités de la classe Vente. Elle est responsable de connaître tous les détails (l’API distincte et immuable) de chaque calculateur de taxes externe, puisqu’elle communique directement (il y a du couplage) à ces derniers.

Changements proposés :

> Ça nuirait à la clarté du code, et la méthode qui contient tout ce code manque de cohésion. Même si l’on faisait une méthode pour encapsuler le code de chaque branche, ça ferait toujours augmenter les responsabilités de la classe Vente. Elle est responsable de connaître tous les détails (l’API distincte et immuable) de chaque calculateur de taxes externe, puisqu’elle communique directement (il y a du couplage) à ces derniers.

**Comment by fuhrmanator** [comment]
Les changements sont petits finalement:
![image](https://user-images.githubusercontent.com/7606540/217910180-fa4a090a-f533-4de4-b0b4-8a0dcd87527d.png)

Plutôt que de parler de cohésion d'une méthode (?) je préfère mentionner la cohésion de la classe Vente après qu'on mentionne les pb des responsabilités.

> Ça nuirait à la **clarté** du code, et la méthode qui contient tout ce code deviendrait de plus en plus longue.
Même si l'on faisait une méthode pour encapsuler le code de chaque branche, ça ferait toujours augmenter les responsabilités de la classe Vente. Elle est responsable de connaître tous les détails (l'API distincte et immuable) de chaque calculateur de taxes externe, puisqu'elle communique directement (il y a du couplage) à ces derniers. **Lorsqu'une classe prend plus de responsabilités, ça porte atteinte à sa cohésion.**

**Comment by Olon11** [comment]
Je suis d'accord avec ces changements. Il reste à adresser ce point : 

> Pour bien définir le problème, il faut expliquer pourquoi on voudrait utiliser plusieurs calculateurs de taxes. Je ne connais pas le domaine des calculateurs de taxes, mais j'imagine que certains calculateurs ne supportent pas toutes les régions (ex.: un multinationale avec un seul système POS) ou les produits.

**Comment by fuhrmanator** [comment]
OK j'ai manque ton premier commentaire.

Le besoin des calculateurs provient de ce problème: on veut permettre au client (disons la compagnie Metro ou Loblaws ou Giant Eagle) qui achète le NextGen POS la possibilité d'utiliser son propre calculateur de taxes, car on vise un marché large (l'Amérique du nord) et chaque région a ses propres lois fiscales (qui changent pratiquement à chaque élection). Le Québec a deux taxes (fédérales et provinciales), etc. et la compagnie NextGen ne veut pas prendre la responsabilité de faire son propre module qui suit tous ces changements des régions de tout son marché. 

Je vais écrire un texte à ce propos pour mieux expliquer.

**Comment by Olon11** [comment]
> Je vais écrire un texte à ce propos pour mieux expliquer.

Il manque cette partie dans 1a5074f

**Comment by fuhrmanator** [comment]
Le changement arrive - voici le résultat.

![image](https://user-images.githubusercontent.com/7606540/218219716-479d400b-99ee-488c-90c0-21867a4cad94.png)
