### ISSUE TITLE
Dans la figure 16.2, est-ce que les couleurs des étapes veulent dire quelque chose?

### ISSUE THREAD

**Issue by Olon11** [fuhrmanator/log210-ndc-quarto#80]
Est-ce que le rouge et le gris ont une certaine signification?

**Comment by fuhrmanator** [comment]
C'est pour tirer l'attention sur les activités importantes. J'ai ajouté les parenthèses pour indiquer la couleur:

> Ce diagramme explique comment GitHub Classroom permet à l'étudiant ou étudiante qui accepte un devoir (*assignment* en anglais) sur GitHub Classroom de choisir son identité universitaire (activité en couleur rose), mais seulement si l'enseignant ou enseignante a téléversé la liste de classe (activité en couleur rose) *avant* d'envoyer les invitations à la communauté étudiante.
