### ISSUE TITLE
Dans la section 19, que veux dire cette icône?

### ISSUE THREAD

**Issue by Olon11** [fuhrmanator/log210-ndc-quarto#82]
![image](https://user-images.githubusercontent.com/15785239/215889081-ac5edd16-d4f6-4bb7-8d8e-0c9e05cc5cf4.png)

Elle n'a pas été expliquée dans le préface,

**Comment by fuhrmanator** [comment]
Bonne question ... 🤔 Under construction? -- je la supprime.
