### ISSUE TITLE
La figure 19.1 n'est pas à jour

### ISSUE THREAD

**Issue by Olon11** [fuhrmanator/log210-ndc-quarto#84]
La figure la plus à jour est dans l'énoncé du laboratoire 1 : https://github.com/profcfuhrmanets/log210-enonce-lab1/blob/main/README/deploiement.svg

**Comment by fuhrmanator** [comment]
Au contraire, la figure SVG que tu cites n'est pas à jour. Surtout qu'il manque le fait que SGB soit une destination des résultats. J'ai perdu le suivi des énoncés de lab1 faute de temps. Il faudra signaler ça dans le dépôt du lab1.

**Comment by Olon11** [comment]
On devrait, dans ce cas, traduire « browser » par « navigateur ».

**Comment by fuhrmanator** [comment]
En effet, j'ai oublié que tu ne vois pas la version dans la branche /issue72 (toutes les corrections de la réviseure):
![image](https://user-images.githubusercontent.com/7606540/215893709-837700e6-28fa-40f8-9853-be7c3d609d99.png)
