### ISSUE TITLE
Dans la section 20.5, le lien vers la traduction du texte sur les parasites et les mollassons n'est pas accessible pour les comptes à l'extérieur de l'ÉTS

### ISSUE THREAD

**Issue by Olon11** [fuhrmanator/log210-ndc-quarto#87]
Pas pratique pour un manuel public 😛.

Le lien en question : https://docs.google.com/document/d/e/2PACX-1vRWTtdcGjUg34gqB6CW_EMt0H28Cgunq09_7HxMUoTLGERjUcQXBHlrYyB76PYJGjtaoYJhhsHS1Tjj/pub

**Comment by fuhrmanator** [comment]
On n'a pas eu la permission d'en faire une traduction à diffuser dans une REL. Je vais supprimer ce lien.

**Comment by fuhrmanator** [comment]
Finalement, la traduction n'est pas incluse dans la REL et donc j'ai rendu publique le lien de la traduction. Puisque la traduction est sur un autre site (qui est maintenant accessible à tout le monde) le problème est réglé.
