### ISSUE TITLE
Expliquer pourquoi la séparation des couches

### ISSUE THREAD

**Issue by fuhrmanator** [fuhrmanator/log210-ndc-quarto#99]
> Devrions-nous avoir une autre FAQ?

Ça serait une bonne idée.

> Ça me fait penser à cette présentation...

C'est une bonne présentation pour expliquer comment les diagrammes sont utilisés dans le code. Elle explique aussi pourquoi on veut la sépartion des couches. En bref, on sépare les couches, parce que :

- on veut améliorer la cohésion du domaine
- on veut réduire le couplage entre la couche présentation et la couche domaine
- la couche présentation évolue plus rapidement que la couche domaine
- il peut y avoir plusieurs couches de présentation (ex.: site web, app mobile)
- on peut ouvrir l'API à des systèmes externes
- on veut améliorer la réutilisation du code pour appeler la même API à plusieurs endroits dans le code (patron commande) ou réutiliser les classes dans un autre projet
- c'est plus simple à tester (en lien avec le point 1 et 2)
- c'est moins long à implémenter et modifier (en lien avec le point 1 et 2)
- ça rend l'application plus simple à comprendre (ex.: pour les nouveaux développeurs) (en lien avec le point 1 et 2)

Avec les figures et les exemples de code de la présentation, ce serait clair et complet.

_Originally posted by @Olon11 in https://github.com/fuhrmanator/log210-ndc-quarto/issues/53#issuecomment-1425021474_

**Comment by fuhrmanator** [comment]
@Olon11 que penses-tu de https://github.com/fuhrmanator/log210-ndc-quarto/pull/100/files

![image](https://user-images.githubusercontent.com/7606540/218225268-ed821e6f-6266-4440-9e05-b35691cba3ff.png)

![image](https://user-images.githubusercontent.com/7606540/218225307-5a0290df-3c2a-4677-85cf-e61084162cff.png)

![image](https://user-images.githubusercontent.com/7606540/218225344-f67b703c-7105-4da3-9354-cbb428b840d0.png)

**Comment by Olon11** [comment]
C'est très bien!
